TFP-3838: Tilrettelegger for å bruke omfordelt og saksbehandlet refus…
navikt/folketrygdloven-beregningsgrunnlag-regelmodell pull request #150
Opened 2020-10-25 15:46 UTC by pekern

…jon i regelmodellen

2020-10-25 15:54 UTC, pekern commented
Fordi vi nå skal begynne å lagre refusjon på forskjellige felter avhengig av om det er orginalt refusjonskrav, saksbehandlet i refusjonsteget eller satt i fordelsteget må vi gjøre endringer i regelmodellen for å tilpasse dette. Ideelt sett trenger ikke regelmodellen vite om andre refusjonskrav enn det som er gjeldende. Men fordi kalkulus bygger opp beregningsgrunnlagandeler utifra regelmodellen må denne modellen ha alle felter som skal ligge på andelene, eller mister vi data når vi mapper frem og tilbake fra regelmodellen.

Det skal sies at det er kun metoden getGjeldendeRefusjon som brukes i regelmodellen, ikke getSaksbehandletRefusjon, getFordeltRefusjon eller getRefusjonskravPrÅr så det er altså ikke brukt til noe annet enn dette formålet. Det ligger allerede felter på regelmodellen som ikke brukes av regelmodellen selv men som kun brukes av kalkulus for å bygge opp andeler igjen på vei ut av regelmodellen. Jeg tenker dette er et pattern vi antakelig vil vekk fra men det er en for stor jobb å ta i denne historien. 

@espenjv Jeg har også endret at vi legger ny refusjon i fordelsteget på fordeltRefusjon istedenfor refusjonskravPrÅr, blir ikke det mer riktig?

2020-10-28 10:37 UTC, mrsladek approved these changes

2020-11-04 11:22 UTC, espenjv requested changes
saksbehandletRefusjonPrÅr/fordeltRefusjonPrÅr blir vel aldri endret inne i regelen, så denne trenger vi ikkje mappe inn.

2020-11-05 12:08 UTC, espenjv approved these changes

2020-11-06 07:25 UTC, merged