Regel og modell for besteberegning
navikt/folketrygdloven-beregningsgrunnlag-regelmodell pull request #154
Opened 2020-12-01 12:37 UTC by espenjv

2020-12-01 14:56 UTC, pekern requested changes

2020-12-01 14:56 UTC, pekern commented on src/main/java/no/nav/folketrygdloven/besteberegning/FastsettBesteberegningGrunnlag.java
> +				.collect(Collectors.toMap(
Hmm, kan man ikke bruke groupBy her? 
besteMåneder.stream().flatMap(beregnetMånedsgrunnlag -> beregnetMånedsgrunnlag.getInntekter().stream())
				.collect(Collectors.groupingBy(Inntekt::getAktivitetNøkkel))

2020-12-01 14:56 UTC, pekern commented on src/main/java/no/nav/folketrygdloven/besteberegning/modell/output/AktivitetNøkkel.java
> +	private Aktivitet type;
disse kan vel være final siden de alltid instansieres

2020-12-01 14:56 UTC, pekern commented on src/main/java/no/nav/folketrygdloven/besteberegning/FinnBesteMåneder.java
> +    static final String ID = "FP_BR XX";
Hvis disse havner i regelloggen må vi nok ordne dette før vi merger?

2020-12-01 14:56 UTC, pekern commented on src/main/java/no/nav/folketrygdloven/besteberegning/FastsettBesteberegningGrunnlag.java
> +    static final String ID = "FP_BR XX";
Hvis disse havner i regelloggen må vi nok ordne dette før vi merger?

2020-12-01 14:56 UTC, pekern commented on src/main/java/no/nav/folketrygdloven/besteberegning/FastsettBesteberegningGrunnlag.java
> +    static final String BESKRIVELSE = "Fastsett grunnlag basert på de 6 beste måneder av de 10 siste";
Kanskje definere hva vi mener med "beste", det er vel de 6 månedene av de siste 10 som har høyest brutto

2020-12-01 14:56 UTC, pekern commented on src/main/java/no/nav/folketrygdloven/besteberegning/FastsettBesteberegningGrunnlag.java
> +    static final String BESKRIVELSE = "Fastsett grunnlag basert på de 6 beste måneder av de 10 siste";
Evt de månedene som har et partall antall dager i seg, hvis det er det du mener med beste

2020-12-01 14:56 UTC, pekern commented on src/main/java/no/nav/folketrygdloven/besteberegning/FinnBesteMåneder.java
> +    static final String BESKRIVELSE = "Finn 6 beste måneder av de 10 siste";
Samme her med "beste"

2020-12-01 19:49 UTC, espenjv commented on src/main/java/no/nav/folketrygdloven/besteberegning/FinnBesteMåneder.java
> +    static final String ID = "FP_BR XX";
Ja, eg kan jo kanskje berre velge ein ny id-serie som er besteberegning

2020-12-02 09:03 UTC, pekern approved these changes

2020-12-02 09:04 UTC, merged